#%RAML 1.0 NamedExample

value:
  id: "2"
  firstName: "name"
  lastName : "lName"
  address : "test address"
  country : "India"
  postal : "122021"
  miles : 15
  creationDate : 2002-10-02T10:00:00-05:00
  userType: "personal"
